### ISSUE TITLE
z-index too low

### ISSUE THREAD

**Issue by coolkau** [teamtv/streamlit_modal#2]
The modal is disappearing behind the sidebar. It would be great to have the modal either on the side of the sidebar or on top.
To be on top it needs to be more than 999991, ie the z-index of the sidebar.

Apart from that cool component; I did not think it was possible currently.

**Comment by koenvo** [comment]
Hi @coolkau . Could you create a pull request for this?

**Comment by coolkau** [comment]
I suggested a change but as noted in the comment I am well versed in css.

**Comment by koenvo** [comment]
Fixed in https://github.com/teamtv/streamlit_modal/pull/3 Thanks!
